export default [
  {
    id: "1",
    name: "Anaya",
    age: 24,
    gender: "F",
    bio: "Perfect Match based on your preferences and interests",
    tags: [],
    avatar: require("../assets/images/Bingle.png"),
  },
  {
    id: "2",
    name: "Riya",
    age: 26,
    gender: "F",
    bio: "",
    tags: ["Travel", "Music", "Fitness"],
    avatar: require("../assets/images/Bingle.png"),
  },
  {
    id: "3",
    name: "Meera",
    age: 25,
    gender: "F",
    bio: "",
    tags: ["Art", "Dance", "Foodie"],
    avatar: require("../assets/images/Bingle.png"),
  },
  {
    id: "4",
    name: "Jeera",
    age: 65,
    gender: "F",
    bio: "",
    tags: ["Art", "Dance", "Foodie"],
    avatar: require("../assets/images/Bingle.png"),
  },
  {
    id: "5",
    name: "Aleera",
    age: 20,
    gender: "F",
    bio: "",
    tags: ["Gym", "Foodie"],
    avatar: require("../assets/images/Bingle.png"),
  },
  {
    id: "6",
    name: "Boramin",
    age: 28,
    gender: "F",
    bio: "",
    tags: ["Gym", "Dance", "Foodie"],
    avatar: require("../assets/images/Bingle.png"),
  },
];
